version: '2'
services:
  couchdb:
    image: "couchdb"
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=pass
    volumes:
        - ./couchdb-dados:/usr/local/var/lib/couchdb
    ports:
     - "5984:5984"
  fauxton:
    image: 3apaxicom/fauxton
    ports:
      - "8984:8000"
    links:
      - couchdb:db
    command:
      - sh
      - "-c"
      - "fauxton -c http://db:5984"
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "8090:80"
  node:
#    build: .
    ports:
     - "80:3000"
    links:
      - couchdb:couchdb
    environment:
      - CODE_REVIEW_HOST=git
      - CODE_REVIEW_PROJECT_ID=123
      - CODE_REVIEW_PRIVATE_TOKEN=EsspXz7kinZN9RayS8sG
      - CODE_REVIEW_COUCHDB_HOST=couchdb
    volumes:
     - ../back-end-node:/projeto
