version: '2'
services:
  php:
    build: .
    ports:
     - "80:80"
    volumes:
     - ..:/var/www/html/
  couchdb:
    image: "couchdb"
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=pass
    volumes:
        - ./couchdb-dados:/usr/local/var/lib/couchdb
    ports:
     - "5984:5984"
  fauxton:
    image: 3apaxicom/fauxton
    ports:
      - 8984:8000
    links:
      - couchdb:db
    command:
      - sh
      - "-c"
      - "fauxton -c http://db:5984"