version: '2'
services:

  couchdb:
    image: "couchdb"
    environment:
      - COUCHDB_USER=root      # altere no node, abaixo, também
      - COUCHDB_PASSWORD=pass  # altere no node, abaixo, também
    volumes:
        - ./couchdb-dados:/usr/local/var/lib/couchdb
    ports:
     - "5984:5984"
  fauxton:
    image: 3apaxicom/fauxton
    ports:
      - "8984:8000"
    links:
      - couchdb:db
    command:
      - sh
      - "-c"
      - "fauxton -c http://db:5984"

  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "8090:80"

  # serve tanto o back-end quanto o front-end
  node:
    image: node:7
    ports:
     - "8093:3000"
    links:
      - couchdb:couchdb
    environment:
      - CODE_REVIEW_HOST=git
      - CODE_REVIEW_PROJECT_ID=123
      - CODE_REVIEW_PRIVATE_TOKEN=EsspXz7kinZN9RayS8sG
      - CODE_REVIEW_COUCHDB_HOST=couchdb
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=pass
    volumes:
     - ../back-end-node:/projeto
    working_dir: /projeto
    command: bash -c "npm install && npm run cors && npm start"

  nginx:
    build: ./nginx
    links:
        - gitlab:gitlab
        - node:node
    ports:
        - "80:80"