version: '2'
services:

  couchdb:
    image: "couchdb"
    environment:
      - COUCHDB_USER=root      # altere no node, abaixo, também
      - COUCHDB_PASSWORD=pass  # altere no node, abaixo, também
    volumes:
        - /dados/couchdb-dados:/usr/local/var/lib/couchdb
    ports:
     - "5984:5984"
    networks:
     - code-review-network
  fauxton:
    image: 3apaxicom/fauxton
    ports:
      - "8984:8000"
    links:
      - couchdb:db
    networks:
      - code-review-network
    command:
      - sh
      - "-c"
      - "fauxton -c http://db:5984"

  # Adicionar como webhook:
  # http://git/sti/sagas2/settings/integrations
  # http://srv-codereview/back-end-review/rpc/webhook
  # gitlab:
  #   image: gitlab/gitlab-ce
  #   ports:
  #     - "8090:80"
  #   networks:
  #     - code-review-network
  #   logging:
  #     driver: "none"

  # serve tanto o back-end quanto o front-end
  back-end-node:
    image: node:7
    ports:
     - "8093:3000"
    links:
      - couchdb:couchdb
#      - gitlab:git
    networks:
      - code-review-network
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=pass
      - COUCHDB_HOST=couchdb

      - GITLAB_HOST=git

      - GITLAB_HOST_PROJECT_ID=123
      - GITLAB_HOST_PRIVATE_TOKEN=X_zfYU5k2VwDx2KegmdQ
#      - xGITLAB_HOST_PROJECT_ID=3
#      - xGITLAB_HOST_PRIVATE_TOKEN=M3_6_x-z3HQEPc4Z4TYg
    volumes:
     - ../back-end-node:/projeto
    working_dir: /projeto
    command: bash -c "npm install && npm run couchdb-setup && npm start"

  srv-codereview:
    build: ./nginx
    ports:
        - "80:80"
    links:
#        - gitlab:git
        - back-end-node:node
    networks:
        - code-review-network

networks:
  code-review-network:
    driver: bridge